
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
    - name: SF_DBT_RAW_LAYAR_TBALES
      database: SF_DBT_UAT
      schema: SF_DBT_RAW_LAYAR
      tables:
        - name: BOTL
        - name: CARS
        - name: COST
        - name: DIST
        - name: HIGHEST_GRADE
        - name: MY_FIRST_DBT_MODEL
        - name: MY_SECOND_DBT_MODEL
        - name: SALES
